#! /bin/bash

 
# Copyright 2015 Giménez, Christian

# Author: Giménez, Christian   

# check-all.sh

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


. script/console-commands.sh

# Check if already running/port blocked
chk_service()
{
  port=${1:?Missing port}
  case $os in
  *[Bb][Ss][Dd]*|Darwin)
      ## checks ipv[46]
      netstat -anL | awk '{print $2}' | grep "\.$1$"
  ;;
  *)
      # Is someone listening on the ports already? (ipv4 only test ?)
      netstat -nl | grep '[^:]:'$port'[ \t]'
  ;;
  esac
}

# ensure right directory
status "Checking if we're in the right direcotry."
realpath=$( ruby -e "puts File.expand_path(\"$0\")")
cd $(dirname $realpath)/..

#Warn if legacy config exists
if [ -e "config/script_server.yml" ]
then
  warning "config/script_server.yml was merged into config/diaspora.yml. Please read the changelog!"
fi

# Check if database.yml exists
if [ ! -e "config/database.yml" ]
then
  fatal "config/database.yml is missing! Copy over config/database.yml.example to config/database.yml and edit it properly!"
fi

# Check if diaspora.yml exists
if [ ! -e "config/diaspora.yml" ]
then
  fatal "config/diaspora.yml is missing! Copy over config/diaspora.yml.example to config/diaspora.yml and edit it properly!"
fi

status "Checking git versioning stuff."
command -v git > /dev/null 2>&1
if [ $? -eq 0 ]; then
  # Check if git merge is in progress
  if [ -f .git/MERGE_MODE ]; then
    fatal "A git merge is in progress!"
  fi

  # Check if detached head state
  git_branch_name="$(git symbolic-ref HEAD 2>/dev/null)"
  if [ -z "$git_branch_name" ];
  then
    warning "You are in detached HEAD state!"
  fi
fi

# Do RVM checks if RVM is being used
status "Checking RVM status."
command -v rvm > /dev/null 2>&1
if [ $? -eq 0 ]; then
  rvm_gemset="$(rvm current | cut -d"@" -f2)"
  project_gemset="$(cat .ruby-gemset | tr -d " \t\n\r")"
  if [ "$rvm_gemset" != "$project_gemset" ]; then
    warning "Project gemset is $project_gemset but you are using $rvm_gemset"
  fi
fi

# Check if bundle is complete
status "Checking if bundle is complete."
if ! bundle check > /dev/null
then
  fatal "Your bundle is not up to date, run the command \"bundle install\""
fi

# Setup environment
status "Setting up environment."
if [ -z "$RAILS_ENV" ]
then
  RAILS_ENV=$(bin/bundle exec ruby ./script/get_config.rb server.rails_environment)
  on_failure "Couldn't parse config/diaspora.yml!"
  export RAILS_ENV
fi


os=$(uname -s)
vars=$(bin/bundle exec ruby ./script/get_config.rb \
  port=server.port \
  single_process_mode=environment.single_process_mode? \
  embed_sidekiq_worker=server.embed_sidekiq_worker \
  workers=server.sidekiq_workers \
  chat=chat.enabled \
  chat_server=chat.server.enabled \
  chat_bosh_proxy=chat.server.bosh.proxy
)
on_failure "Couldn't parse config/diaspora.yml!"
eval "$vars"

if [ -n "$DB" ]
then
  export DB
fi

status "Checking the port situation."
if [ -z "$PORT" -a -n "$port" ]
then
  warning "Setting port via configuration is deprecated, set listen instead. See the updated config/diaspora.yml.example."
  PORT="$port"
fi

args="$@"
for arg in $(echo $args | awk '{ for (i = 1; i <= NF; i++) print $i}')
do
  [ "$prev_arg" = '-p' ] && PORT="$arg"
  prev_arg="$arg"
done

if [ -n "$PORT" ]
then
  export PORT

  services=$(chk_service $PORT)
  if [ -n "$services" ]
  then
    fatal "Port $port is already in use.\n\t$services"
  fi
fi

# Check AGPL
status "Checking for public/source.tar.gz (Check AGPL licence)"
if [ -w "public" -a ! -e  "public/source.tar.gz" ]
then
  if command -v git > /dev/null 2>&1 && git rev-parse --is-inside-work-tree > /dev/null 2>&1
  then
      status "Creating public/source.tar.gz... Please wait."
      commit_sha=$(git rev-parse HEAD)      
      tar czf public/source.tar.gz  $(git ls-tree -r $commit_sha | awk '{print $4}')
  else
      # No need for being so rude, just warning and that's all...
      warning "Can't generate public/source.tar.gz for you.
Please tar up a copy of your Diaspora installation and place it there."
  fi
fi

if [ ! -e "public/source.tar.gz" ]
then
    warning "Can't find public/source.tar.gz.

For AGPL licence obligations, we strongly suggest you tar up a copy of your Diaspora installation and place it there."
fi

# Check if assets are precompiled
status "Check if assets was precompiled..."
if [ "$RAILS_ENV" = "production" -a -z "$(find public/assets -maxdepth 1 -name 'home-*.css' -print -quit 2>/dev/null)" ]
then
  fatal "You're running in production mode without having assets
precompiled. Now and after each update before you restart the
application, run:
    bin/rake assets:precompile"
fi

# Check for old curl versions (see https://github.com/diaspora/diaspora/issues/4202)
status "Checking for old curl versions."
if [ `curl -V | grep AsynchDNS | wc -l` -ne 1 ]
then
  warning "
*****************************************************************
curl does not support async DNS, this can cause Sidekiq to crash!
Please update curl to version 7.32, see issue
https://github.com/diaspora/diaspora/issues/4202 for details
*****************************************************************
"
fi

if [ "$chat" = "true" -a "$chat_server" = "true" -a  "$chat_bosh_proxy" = "false" ]
then
  warning "
*****************************************************************
You enabled the chat feature but haven't configured BOSH! That
could lead to mixed-content problems with the http clients. Please
think about editing your proxy configuration as described in:

diaspora.yml.example
*****************************************************************
"
fi

# Start Diaspora
status "Starting Diaspora in $RAILS_ENV mode "
if [ -n "$PORT" ]
then
  printf "on port $PORT "
fi
if [ "$embed_sidekiq_worker" = "true" ]
then
  echo "with a Sidekiq worker embedded into Unicorn."
  workers=0
elif [ "$single_process_mode" = "true" ]
then
  echo "with job processing inside the request cycle."
  workers=0
else
  echo "with $workers Sidekiq worker(s)."
fi
echo ""

status "Check done."
