#!/bin/sh
#   Copyright (c) 2010-2011, Diaspora Inc.  This file is
#   licensed under the Affero General Public License version 3 or later.  See
#   the COPYRIGHT file.

. script/console-commands.sh

status "Launching sidekiq..."
bin/bundle exec sidekiq > log/sidekiq-last-run.log &

if [ "$chat" = "true" -a "$chat_server" = "true" ]
then
    status "Launching vines... Yay! You're using XMPP!!!" 
    bin/bundle exec vines start > log/vines-las-run.log &
fi

echo -e "Question: Have you used $green nohup $white for starting this script? maybe you should consider that... 
Like this: $green nohup script/server & $white"

status "Launching unicorn..."
bin/bundle exec unicorn -c config/unicorn.rb


